// ------------------------------------------------------------------------------
// <auto-generated>
// Ce code a été généré par un outil.
// Version du runtime :4.0.30319.42000
// 
// Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
// le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace FCGP.Properties
{

    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    /// <summary>
    /// Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        /// <summary>
        /// Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("FCGP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Remplace la propriété CurrentUICulture du thread actuel pour toutes
        /// les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] Aide_FCGP_REGROUPER
        {
            get
            {
                var obj = ResourceManager.GetObject("Aide_FCGP_REGROUPER", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap AjouterCartesRegroupement
        {
            get
            {
                var obj = ResourceManager.GetObject("AjouterCartesRegroupement", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap CapturerCarte
        {
            get
            {
                var obj = ResourceManager.GetObject("CapturerCarte", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap CreerRegroupement
        {
            get
            {
                var obj = ResourceManager.GetObject("CreerRegroupement", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] FRefAgrandir_HD_BG
        {
            get
            {
                var obj = ResourceManager.GetObject("FRefAgrandir_HD_BG", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] FRefAgrandir_HG_BD
        {
            get
            {
                var obj = ResourceManager.GetObject("FRefAgrandir_HG_BD", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] FRefAgrandir_Horizontal
        {
            get
            {
                var obj = ResourceManager.GetObject("FRefAgrandir_Horizontal", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] FRefAgrandir_Vertical
        {
            get
            {
                var obj = ResourceManager.GetObject("FRefAgrandir_Vertical", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] FRefDeplacer
        {
            get
            {
                var obj = ResourceManager.GetObject("FRefDeplacer", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] FRefDeplacer_Horizontal
        {
            get
            {
                var obj = ResourceManager.GetObject("FRefDeplacer_Horizontal", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] FRefDeplacer_Vertical
        {
            get
            {
                var obj = ResourceManager.GetObject("FRefDeplacer_Vertical", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Mode_Deplacement
        {
            get
            {
                var obj = ResourceManager.GetObject("Mode_Deplacement", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeCarteDefaut
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeCarteDefaut", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeCarteDeplacement
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeCarteDeplacement", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeCarteDeplacementHorizontal
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeCarteDeplacementHorizontal", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeCarteDeplacementVertical
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeCarteDeplacementVertical", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeCarteDeplacementVHS
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeCarteDeplacementVHS", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeCarteDeplacementVSH
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeCarteDeplacementVSH", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeTraceCouper
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeTraceCouper", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeTraceCouperPtSeg
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeTraceCouperPtSeg", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeTraceDefaut
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeTraceDefaut", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeTraceDeplacement
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeTraceDeplacement", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeTraceDeplacerPt
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeTraceDeplacerPt", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeTraceEditer
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeTraceEditer", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeTraceInsererPtSeg
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeTraceInsererPtSeg", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeTraceSupprimer
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeTraceSupprimer", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ModeTraceSupprimerPtSeg
        {
            get
            {
                var obj = ResourceManager.GetObject("ModeTraceSupprimerPtSeg", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap RegarderPlanRegroupement
        {
            get
            {
                var obj = ResourceManager.GetObject("RegarderPlanRegroupement", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] Zoom
        {
            get
            {
                var obj = ResourceManager.GetObject("Zoom", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ZOOM_COULEUR
        {
            get
            {
                var obj = ResourceManager.GetObject("ZOOM_COULEUR", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ZOOM_MOINS_COULEUR
        {
            get
            {
                var obj = ResourceManager.GetObject("ZOOM_MOINS_COULEUR", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ZOOM_PLUS_COULEUR
        {
            get
            {
                var obj = ResourceManager.GetObject("ZOOM_PLUS_COULEUR", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}